/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as NouveauMotDePasseRouteImport } from './routes/nouveau-mot-de-passe'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AppAbonnementRouteImport } from './routes/_app.abonnement'
import { Route as AppAccueilRouteImport } from './routes/_app.accueil'
import { Route as AppAideRouteImport } from './routes/_app.aide'
import { Route as AppCommunauteRouteImport } from './routes/_app.communaute'
import { Route as AppDecouvrirRouteImport } from './routes/_app.decouvrir'
import { Route as AppDemandesRouteImport } from './routes/_app.demandes'
import { Route as AppGuideRouteImport } from './routes/_app.guide'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppParrainageRouteImport } from './routes/_app.parrainage'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAbonnementsRouteImport } from './routes/admin.abonnements'
import { Route as AdminAffiliationRouteImport } from './routes/admin.affiliation'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminContenusRouteImport } from './routes/admin.contenus'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminMetaAdsRouteImport } from './routes/admin.meta-ads'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as RencontreChretiennePaysRouteImport } from './routes/rencontre-chretienne.$pays'
import { Route as AppParametresBloquesRouteImport } from './routes/_app.parametres.bloques'
import { Route as AppParametresLangueRouteImport } from './routes/_app.parametres.langue'
import { Route as AppParametresNotificationsRouteImport } from './routes/_app.parametres.notifications'
import { Route as AppParametresSecuriteRouteImport } from './routes/_app.parametres.securite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveauMotDePasseRoute = NouveauMotDePasseRouteImport.update({
  id: '/nouveau-mot-de-passe',
  path: '/nouveau-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAbonnementRoute = AppAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AppRoute,
} as any)
const AppAccueilRoute = AppAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AppRoute,
} as any)
const AppAideRoute = AppAideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunauteRoute = AppCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => AppRoute,
} as any)
const AppDecouvrirRoute = AppDecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandesRoute = AppDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppParrainageRoute = AppParrainageRouteImport.update({
  id: '/parrainage',
  path: '/parrainage',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbonnementsRoute = AdminAbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliationRoute = AdminAffiliationRouteImport.update({
  id: '/affiliation',
  path: '/affiliation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContenusRoute = AdminContenusRouteImport.update({
  id: '/contenus',
  path: '/contenus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetaAdsRoute = AdminMetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RencontreChretiennePaysRoute = RencontreChretiennePaysRouteImport.update({
  id: '/rencontre-chretienne/$pays',
  path: '/rencontre-chretienne/$pays',
  getParentRoute: () => rootRouteImport,
} as any)
const AppParametresBloquesRoute = AppParametresBloquesRouteImport.update({
  id: '/parametres/bloques',
  path: '/parametres/bloques',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresLangueRoute = AppParametresLangueRouteImport.update({
  id: '/parametres/langue',
  path: '/parametres/langue',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresNotificationsRoute =
  AppParametresNotificationsRouteImport.update({
    id: '/parametres/notifications',
    path: '/parametres/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppParametresSecuriteRoute = AppParametresSecuriteRouteImport.update({
  id: '/parametres/securite',
  path: '/parametres/securite',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/onboarding': typeof OnboardingRoute
  '/tarifs': typeof TarifsRoute
  '/abonnement': typeof AppAbonnementRoute
  '/accueil': typeof AppAccueilRoute
  '/aide': typeof AppAideRoute
  '/communaute': typeof AppCommunauteRoute
  '/decouvrir': typeof AppDecouvrirRoute
  '/demandes': typeof AppDemandesRoute
  '/guide': typeof AppGuideRoute
  '/messages': typeof AppMessagesRoute
  '/parrainage': typeof AppParrainageRoute
  '/profil': typeof AppProfilRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/affiliation': typeof AdminAffiliationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contenus': typeof AdminContenusRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/meta-ads': typeof AdminMetaAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rencontre-chretienne/$pays': typeof RencontreChretiennePaysRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/parametres/bloques': typeof AppParametresBloquesRoute
  '/parametres/langue': typeof AppParametresLangueRoute
  '/parametres/notifications': typeof AppParametresNotificationsRoute
  '/parametres/securite': typeof AppParametresSecuriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/onboarding': typeof OnboardingRoute
  '/tarifs': typeof TarifsRoute
  '/abonnement': typeof AppAbonnementRoute
  '/accueil': typeof AppAccueilRoute
  '/aide': typeof AppAideRoute
  '/communaute': typeof AppCommunauteRoute
  '/decouvrir': typeof AppDecouvrirRoute
  '/demandes': typeof AppDemandesRoute
  '/guide': typeof AppGuideRoute
  '/messages': typeof AppMessagesRoute
  '/parrainage': typeof AppParrainageRoute
  '/profil': typeof AppProfilRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/affiliation': typeof AdminAffiliationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contenus': typeof AdminContenusRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/meta-ads': typeof AdminMetaAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rencontre-chretienne/$pays': typeof RencontreChretiennePaysRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/parametres/bloques': typeof AppParametresBloquesRoute
  '/parametres/langue': typeof AppParametresLangueRoute
  '/parametres/notifications': typeof AppParametresNotificationsRoute
  '/parametres/securite': typeof AppParametresSecuriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/onboarding': typeof OnboardingRoute
  '/tarifs': typeof TarifsRoute
  '/_app/abonnement': typeof AppAbonnementRoute
  '/_app/accueil': typeof AppAccueilRoute
  '/_app/aide': typeof AppAideRoute
  '/_app/communaute': typeof AppCommunauteRoute
  '/_app/decouvrir': typeof AppDecouvrirRoute
  '/_app/demandes': typeof AppDemandesRoute
  '/_app/guide': typeof AppGuideRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/parrainage': typeof AppParrainageRoute
  '/_app/profil': typeof AppProfilRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/affiliation': typeof AdminAffiliationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/contenus': typeof AdminContenusRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/meta-ads': typeof AdminMetaAdsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/rencontre-chretienne/$pays': typeof RencontreChretiennePaysRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/_app/parametres/bloques': typeof AppParametresBloquesRoute
  '/_app/parametres/langue': typeof AppParametresLangueRoute
  '/_app/parametres/notifications': typeof AppParametresNotificationsRoute
  '/_app/parametres/securite': typeof AppParametresSecuriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/conditions'
    | '/confidentialite'
    | '/faq'
    | '/inscription'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/onboarding'
    | '/tarifs'
    | '/abonnement'
    | '/accueil'
    | '/aide'
    | '/communaute'
    | '/decouvrir'
    | '/demandes'
    | '/guide'
    | '/messages'
    | '/parrainage'
    | '/profil'
    | '/admin/abonnements'
    | '/admin/affiliation'
    | '/admin/analytics'
    | '/admin/contenus'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/meta-ads'
    | '/admin/moderation'
    | '/admin/parametres'
    | '/admin/support'
    | '/admin/utilisateurs'
    | '/blog/$slug'
    | '/rencontre-chretienne/$pays'
    | '/admin/'
    | '/blog/'
    | '/parametres/bloques'
    | '/parametres/langue'
    | '/parametres/notifications'
    | '/parametres/securite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions'
    | '/confidentialite'
    | '/faq'
    | '/inscription'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/onboarding'
    | '/tarifs'
    | '/abonnement'
    | '/accueil'
    | '/aide'
    | '/communaute'
    | '/decouvrir'
    | '/demandes'
    | '/guide'
    | '/messages'
    | '/parrainage'
    | '/profil'
    | '/admin/abonnements'
    | '/admin/affiliation'
    | '/admin/analytics'
    | '/admin/contenus'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/meta-ads'
    | '/admin/moderation'
    | '/admin/parametres'
    | '/admin/support'
    | '/admin/utilisateurs'
    | '/blog/$slug'
    | '/rencontre-chretienne/$pays'
    | '/admin'
    | '/blog'
    | '/parametres/bloques'
    | '/parametres/langue'
    | '/parametres/notifications'
    | '/parametres/securite'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/conditions'
    | '/confidentialite'
    | '/faq'
    | '/inscription'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/onboarding'
    | '/tarifs'
    | '/_app/abonnement'
    | '/_app/accueil'
    | '/_app/aide'
    | '/_app/communaute'
    | '/_app/decouvrir'
    | '/_app/demandes'
    | '/_app/guide'
    | '/_app/messages'
    | '/_app/parrainage'
    | '/_app/profil'
    | '/admin/abonnements'
    | '/admin/affiliation'
    | '/admin/analytics'
    | '/admin/contenus'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/meta-ads'
    | '/admin/moderation'
    | '/admin/parametres'
    | '/admin/support'
    | '/admin/utilisateurs'
    | '/blog/$slug'
    | '/rencontre-chretienne/$pays'
    | '/admin/'
    | '/blog/'
    | '/_app/parametres/bloques'
    | '/_app/parametres/langue'
    | '/_app/parametres/notifications'
    | '/_app/parametres/securite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  FaqRoute: typeof FaqRoute
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NouveauMotDePasseRoute: typeof NouveauMotDePasseRoute
  OnboardingRoute: typeof OnboardingRoute
  TarifsRoute: typeof TarifsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RencontreChretiennePaysRoute: typeof RencontreChretiennePaysRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveau-mot-de-passe': {
      id: '/nouveau-mot-de-passe'
      path: '/nouveau-mot-de-passe'
      fullPath: '/nouveau-mot-de-passe'
      preLoaderRoute: typeof NouveauMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/abonnement': {
      id: '/_app/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AppAbonnementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accueil': {
      id: '/_app/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AppAccueilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aide': {
      id: '/_app/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AppAideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communaute': {
      id: '/_app/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof AppCommunauteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decouvrir': {
      id: '/_app/decouvrir'
      path: '/decouvrir'
      fullPath: '/decouvrir'
      preLoaderRoute: typeof AppDecouvrirRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demandes': {
      id: '/_app/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof AppDemandesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide': {
      id: '/_app/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parrainage': {
      id: '/_app/parrainage'
      path: '/parrainage'
      fullPath: '/parrainage'
      preLoaderRoute: typeof AppParrainageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abonnements': {
      id: '/admin/abonnements'
      path: '/abonnements'
      fullPath: '/admin/abonnements'
      preLoaderRoute: typeof AdminAbonnementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliation': {
      id: '/admin/affiliation'
      path: '/affiliation'
      fullPath: '/admin/affiliation'
      preLoaderRoute: typeof AdminAffiliationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contenus': {
      id: '/admin/contenus'
      path: '/contenus'
      fullPath: '/admin/contenus'
      preLoaderRoute: typeof AdminContenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meta-ads': {
      id: '/admin/meta-ads'
      path: '/meta-ads'
      fullPath: '/admin/meta-ads'
      preLoaderRoute: typeof AdminMetaAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rencontre-chretienne/$pays': {
      id: '/rencontre-chretienne/$pays'
      path: '/rencontre-chretienne/$pays'
      fullPath: '/rencontre-chretienne/$pays'
      preLoaderRoute: typeof RencontreChretiennePaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/parametres/bloques': {
      id: '/_app/parametres/bloques'
      path: '/parametres/bloques'
      fullPath: '/parametres/bloques'
      preLoaderRoute: typeof AppParametresBloquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/langue': {
      id: '/_app/parametres/langue'
      path: '/parametres/langue'
      fullPath: '/parametres/langue'
      preLoaderRoute: typeof AppParametresLangueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/notifications': {
      id: '/_app/parametres/notifications'
      path: '/parametres/notifications'
      fullPath: '/parametres/notifications'
      preLoaderRoute: typeof AppParametresNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametres/securite': {
      id: '/_app/parametres/securite'
      path: '/parametres/securite'
      fullPath: '/parametres/securite'
      preLoaderRoute: typeof AppParametresSecuriteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAbonnementRoute: typeof AppAbonnementRoute
  AppAccueilRoute: typeof AppAccueilRoute
  AppAideRoute: typeof AppAideRoute
  AppCommunauteRoute: typeof AppCommunauteRoute
  AppDecouvrirRoute: typeof AppDecouvrirRoute
  AppDemandesRoute: typeof AppDemandesRoute
  AppGuideRoute: typeof AppGuideRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppParrainageRoute: typeof AppParrainageRoute
  AppProfilRoute: typeof AppProfilRoute
  AppParametresBloquesRoute: typeof AppParametresBloquesRoute
  AppParametresLangueRoute: typeof AppParametresLangueRoute
  AppParametresNotificationsRoute: typeof AppParametresNotificationsRoute
  AppParametresSecuriteRoute: typeof AppParametresSecuriteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbonnementRoute: AppAbonnementRoute,
  AppAccueilRoute: AppAccueilRoute,
  AppAideRoute: AppAideRoute,
  AppCommunauteRoute: AppCommunauteRoute,
  AppDecouvrirRoute: AppDecouvrirRoute,
  AppDemandesRoute: AppDemandesRoute,
  AppGuideRoute: AppGuideRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppParrainageRoute: AppParrainageRoute,
  AppProfilRoute: AppProfilRoute,
  AppParametresBloquesRoute: AppParametresBloquesRoute,
  AppParametresLangueRoute: AppParametresLangueRoute,
  AppParametresNotificationsRoute: AppParametresNotificationsRoute,
  AppParametresSecuriteRoute: AppParametresSecuriteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAbonnementsRoute: typeof AdminAbonnementsRoute
  AdminAffiliationRoute: typeof AdminAffiliationRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContenusRoute: typeof AdminContenusRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMetaAdsRoute: typeof AdminMetaAdsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbonnementsRoute: AdminAbonnementsRoute,
  AdminAffiliationRoute: AdminAffiliationRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContenusRoute: AdminContenusRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMetaAdsRoute: AdminMetaAdsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  FaqRoute: FaqRoute,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NouveauMotDePasseRoute: NouveauMotDePasseRoute,
  OnboardingRoute: OnboardingRoute,
  TarifsRoute: TarifsRoute,
  BlogSlugRoute: BlogSlugRoute,
  RencontreChretiennePaysRoute: RencontreChretiennePaysRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
